# Book Publication Workflow Configuration
app:
  name: "Book Publication Workflow"
  version: "1.0.0"
  debug: false

database:
  path: "data/workflow.db"
  backup_interval: 3600  # seconds

publishing:
  platforms:
    - amazon_kdp
    - draft2digital
    - kobo
    - apple_books
  
  formats:
    - epub
    - mobi
    - pdf

automation:
  screenshot_interval: 30  # seconds
  max_retries: 3
  timeout: 60  # seconds

logging:
  level: "INFO"
  file: "logs/workflow.log"
  max_size: "10MB"
  backup_count: 5
